### ISSUE TITLE
Unclear json parse error

### ISSUE THREAD

**Issue by skiesoffire** [robinwelin/gae-version-cleanup#17]
Hello,
I was recently building a new nodejs16 project with your cleanup code and it looks like it fails but does not give an indication what the issue is. I am continuing to investigate ....

Also tried with master tag, same error.

```
Run robinwelin/gae-version-cleanup@v1.0.3
  with:
    GCP_PROJECT: ***
    GCP_APPLICATION_CREDENTIALS: ***
  
    DRY_RUN: true
    SKIP_ALLOCATED: true
    SKIP_COUNT: 2
    SKIP_UNIQUE: true
    SKIP_UNIQUE_COUNT: 2
undefined:1
7*^1jo	G?iG(:***i.^r_buY`zH-zJk
 ^

SyntaxError: Unexpected token * in JSON at position 1
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/home/runner/work/_actions/robinwelin/gae-version-cleanup/v1.0.[3](xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx#step:2:3)/dist/index.js:17136[4](xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx#step:2:4):16)
    at __webpack_require__ (/home/runner/work/_actions/robinwelin/gae-version-cleanup/v1.0.3/dist/index.js:24:31)
    at Object.<anonymous> (/home/runner/work/_actions/robinwelin/gae-version-cleanup/v1.0.3/dist/index.js:[5](xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx#step:2:5)118:34)
    at __webpack_require__ (/home/runner/work/_actions/robinwelin/gae-version-cleanup/v1.0.3/dist/index.js:24:31)
    at startup (/home/runner/work/_actions/robinwelin/gae-version-cleanup/v1.0.3/dist/index.js:43:19)
    at /home/runner/work/_actions/robinwelin/gae-version-cleanup/v1.0.3/dist/index.js:4[7](xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx#step:2:7):1[8](xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx#step:2:8)
    at Object.<anonymous> (/home/runner/work/_actions/robinwelin/gae-version-cleanup/v1.0.3/dist/index.js:50:10)
    at Module._compile (internal/modules/cjs/loader.js:[9](xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx#step:2:9)99:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:[10](xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx#step:2:10)27:10)
```

**Comment by skiesoffire** [comment]
fixed! looks like my cred was not base64 encoded as per your documentation.
It is very odd since in my old project, I don't recall encoding it and google's auth takes the cred straight up. (can't confirm, since I can't read the secret.)

The following code is how I used to set it up and it still works for some reason: 

```
      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
```

```
      - name: "Cleaning up old gae versions"
        uses: robinwelin/gae-version-cleanup@v1.0.3
        with:
          GCP_PROJECT: ${{ secrets.PROJECT_ID }}
          GCP_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
```
